name: Build Kernel

on:
  push:
    tags:
      - '*'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-kernels:
    name: Build all affected Kernels
    permissions:
      contents: read
      packages: read
      actions: write
    secrets:
      s3_access_key: ${{ secrets.GCS_S3_ACCESS_KEY }}
      s3_secret_key: ${{ secrets.GCS_S3_SECRET_KEY }}
    uses: openwrt/actions-shared-workflows/.github/workflows/kernel.yml@main
